export class Config {
  static TELEGRAM_APP_ID = undefined; // YOUR APP ID EX : 324893724923
  static TELEGRAM_APP_HASH = undefined; // YOUR APP HASH EX: "aslkfjkalsjflkasf"
  static USEAUTOUPGRADEBOOST = true; //USE AUTO UPGRADE OR NO (DEFAULT TRUE)
  static USEAUTOTAP = true; //USE AUTO TAP OR NO (DEFAULT TRUE)
  static USEAUTOCOMPLETEMISSIONS = true; //USE AUTO COMPLETE MISSIONS OR NO (DEFAULT TRUE)
  static USEAUTOLEVELUPRANDOMCARD = true; //USE AUTO LEVELUP RANDOM CARD OR NO (DEFAULT TRUE)
  static CUSTOMDELAY = undefined; //CUSTOM DELAY AFTER EXECUTION IN SECOND EX : 60 MEANS 60 SECONDS (DEFAULT DYNAMIC TIME + DELAY RANDOM)
}
